package com.gongyu.service.distribute.game.model.entity;

import java.util.Date;
import com.gongyu.snowcloud.framework.data.mybatis.BaseEntity;
import lombok.Data;

/**
 * 
 * WARNING:
 * this code is generated by code-generator
 * please DO NOT modify this file
 * @author code-generator
 * @date 2020-07-08 11:23:56
 */
@Data
public class PersonAuthRecord extends BaseEntity {
  /**
   * 用户姓名
   */
  private String name;
  /**
   * 身份证号
   */
  private String idCard;
  /**
   * 认证状态 0 未认证 1 认证失败 2 认证成功
   */
  private Integer certifStatus;
  /**
   * 请求状态 0 未请求 1 请求中 2 请求成功 3 请求失败 4 返回成功 5 返回失败
   */
  private Integer reqStatus;
  /**
   * 返回信息
   */
  private String alResultJson;
  /**
   * 创建时间
   */
  private Date createDate;
  /**
   * 更新时间
   */
  private Date updateDate;

  /**
   * 绑定账户ID
   */
  private Long buildUserId;

}
