server:
  servlet:
    context-path: /distribute-game-app
    port: 8080
spring:
  profiles:
    active: dev
    include: mybatis,web,redis,file,doc

logging:
  config: classpath:logback.xml
  level:
    io:
      lettuce:
        core: INFO
    org:
      springframework:
        data:
          redis:
            core: INFO

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_null
      capital-mode: false
      #逻辑删除配置（下面3个配置）
      logic-delete-value: 1
      logic-not-delete-value: 0
      sql-injector: com.baomidou.mybatisplus.extension.injector.LogicSqlInjector
      #公共字段更新
      meta-object-handler: com.gongyu.application.house.handler.BaseMetaObjectHandler
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'null'
    call-setters-on-nulls: true
#    使用com.baomidou.mybatisplus.extension.plugins.PerformanceInterceptor查看SQL日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

game:
  noLoginUrl: /inner/open,/reHome,/redisGet,/users/login,/users/reg,/users/sendCode,/users/getGraphVerifyCode,/users/checkGraphVerifyCode,/member/loginThird,/users/changePass,/member/qrcode,/member/verifyCode,/wx/callback,/ali/callback,
    /version/*,/dict/*,/sysConfig/*,/area/*,/aliyunFile/*,/content/*,/banner/*,/equipment/*,/member/logout,/share/regist,/swagger-resources,/order/create,/article/queryArticle,/users/downUrl
  rootUrl: /**
  signUrl:
    notCheck: /version/query,/aliyunFile/upload,/aliyunFile/batchUpload,/share/regist

#订单未支付超时时间
order_time_out: 1800000
#注册地址+邀请码
register_url: http://app.qmyl8888.com/#/register?inviteCode=%s