server:
  servlet:
    context-path: /distribute-game-oss
  port: 8080
spring:
  profiles:
    active: dev
    include: mybatis,web,redis,file,doc

logging:
  config: classpath:logback.xml

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_null
      capital-mode: false
      #逻辑删除配置（下面3个配置）
      logic-delete-value: 1
      logic-not-delete-value: 0
      sql-injector: com.baomidou.mybatisplus.extension.injector.LogicSqlInjector
      #公共字段更新
      meta-object-handler: com.gongyu.snowcloud.framework.data.mybatis.BaseMetaObjectHandler
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'null'
    call-setters-on-nulls: true
#    使用com.baomidou.mybatisplus.extension.plugins.PerformanceInterceptor查看SQL日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#订单未支付超时时间
order_time_out: 7200000
#注册地址+邀请码
register_url: http://app.qmyl8888.com/#/register?inviteCode=%s