package com.futures.model.entity;

import java.math.BigDecimal;
import java.util.Date;
import com.gongyu.snowcloud.framework.data.mybatis.BaseEntity;
import lombok.Data;

/**
 * 收入记录
 * WARNING:
 * this code is generated by code-generator
 * please DO NOT modify this file
 * @author code-generator
 * @date 2020-06-19 09:54:15
 */
@Data
public class UserIncomRecord extends BaseEntity {
  /**
   * 用户ID
   */
  private Long userId;
  /**
   * 收入金额
   */
  private BigDecimal incom;
  /**
   * 收入类型 1：累计收入 2:推荐收益 3：推广收益
   */
  private Integer incomType;
  /**
   * 创建时间
   */
  private Date createDate;


}
